name: Deploy to Bluehost

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: List files to be deployed
        run: |
          echo "Files in current directory:"
          ls -la
          echo ""
          echo "Files that will be deployed:"
          find . -type f -not -path "./.git*" -not -path "./public_html/*" -not -name "deploy.sh" -not -name "README.md" -not -name ".gitignore" -not -name ".gitattributes" -not -name ".DS_Store"

      - name: Install dependencies (if any)
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Build project (if needed)
        run: |
          if [ -f "package.json" ] && npm run build; then
            echo "Build completed"
          else
            echo "No build step required"
          fi

      - name: Deploy to Bluehost via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.DS_Store
            **/Thumbs.db
            **/public_html/**
            **/deploy.sh
            **/README.md
            **/.gitignore
            **/.gitattributes
          dangerous-clean-slate: false
          log-level: verbose
